import type { Caption } from "@/components/artworks/types";

export const sectionLabels: Record<string, Caption> = {
    characters: {
        es: "Personajes",
        en: "Characters",
        fr: "Personnages",
        pt: "Personagens",
    },
    "10thanniversary": {
        es: "Décimo aniversario",
        en: "10th Anniversary",
        fr: "10e Anniversaire",
        pt: "10º Aniversário",
    },
    ps2: {
        es: "Capturas de PlayStation 2",
        en: "PlayStation 2 screenshots",
        fr: "Captures d’écran PlayStation 2",
        pt: "Capturas de tela da PlayStation 2",
    },
    ps3: {
        es: "Capturas de PlayStation 3",
        en: "PlayStation 3 screenshots",
        fr: "Captures d’écran PlayStation 3",
        pt: "Capturas de tela da PlayStation 3",
    },
    psp: {
        es: "Capturas de PlayStation Portable",
        en: "PlayStation Portable screenshots",
        fr: "Captures d’écran PlayStation Portable",
        pt: "Capturas de tela da PlayStation Portable",
    },
    pc: {
        es: "Capturas de PC",
        en: "PC screenshots",
        fr: "Captures d’écran PC",
        pt: "Capturas de tela de PC",
    },
    xbox: {
        es: "Capturas de Xbox",
        en: "Xbox screenshots",
        fr: "Captures d’écran Xbox",
        pt: "Capturas de tela do Xbox",
    },
    definitiveEdition: {
        es: "Edición Definitiva",
        en: "Definitive Edition",
        fr: "Definitive Edition",
        pt: "Definitive Edition",
    },
    enhanced: {
        es: "Capturas de la versión Enhanced",
        en: "Enhanced version screenshots",
        fr: "Captures d’écran de la version Enhanced",
        pt: "Capturas de tela da versão Enhanced",
    },
    "e&e": {
        es: "Capturas de la versión Expanded & Enhanced",
        en: "Expanded & Enhanced version screenshots",
        fr: "Captures d’écran de la version Expanded & Enhanced",
        pt: "Capturas de tela da versão Expanded & Enhanced",
    },
    iv: {
        es: "Personajes de Grand Theft Auto IV",
        en: "Grand Theft Auto IV characters",
        fr: "Personnages de Grand Theft Auto IV",
        pt: "Personagens de Grand Theft Auto IV",
    },
    tlad: {
        es: "Personajes de The Lost and Damned",
        en: "The Lost and Damned characters",
        fr: "Personnages de The Lost and Damned",
        pt: "Personagens de The Lost and Damned",
    },
    tbogt: {
        es: "Personajes de The Ballad of Gay Tony",
        en: "The Ballad of Gay Tony characters",
        fr: "Personnages de The Ballad of Gay Tony",
        pt: "Personagens de The Ballad of Gay Tony",
    },
    vehicles: {
        es: "Vehículos",
        en: "Vehicles",
        fr: "Véhicules",
        pt: "Veículos",
    },
    wallpapers: {
        es: "Fondos de pantalla",
        en: "Wallpapers",
        fr: "Fonds d’écran",
        pt: "Papéis de parede",
    },
    impoundedVehicles: {
        es: "Vehículos incautados",
        en: "Impounded Vehicles",
        fr: "Véhicules saisis",
        pt: "Veículos apreendidos",
    },
    confiscatedWeapons: {
        es: "Armas confiscadas",
        en: "Confiscated Weapons",
        fr: "Armes confisquées",
        pt: "Armas confiscadas",
    },
    suspiciousBusinesses: {
        es: "Negocios sospechosos",
        en: "Suspicious Businesses",
        fr: "Entreprises suspectes",
        pt: "Negócios suspeitos",
    },
    viceCityCrimeTree: {
        es: "Árbol del crimen de Vice City",
        en: "Vice City Crime Tree",
        fr: "Arbre du crime de Vice City",
        pt: "Árvore do crime de Vice City",
    },
    kentPauls80sNostalgiaZone: {
        es: "Kent Paul's 80's Nostalgia Zone!",
        en: "Kent Paul's 80's Nostalgia Zone!",
        fr: "Kent Paul's 80's Nostalgia Zone!",
        pt: "Kent Paul's 80's Nostalgia Zone!",
    },
    multiplayer: {
        es: "Multijugador",
        en: "Multiplayer",
        fr: "Multijoueur",
        pt: "Multijogador",
    },
    storyMode: {
        es: "Modo historia",
        en: "Story mode",
        fr: "Mode Histoire",
        pt: "Modo história",
    },
    gtaOnline: {
        es: "GTA Online",
        en: "GTA Online",
        fr: "GTA Online",
        pt: "GTA Online",
    },
    prerelease: {
        es: "Capturas de prelanzamiento",
        en: "Pre-release screenshots",
        fr: "Captures d’écran de pré-lancement",
        pt: "Capturas de pré-lançamento",
    },
};
